const fs = require('fs');
const path = require('path');

// Read the products file
const filePath = path.join(__dirname, 'products-updated.json');
const products = JSON.parse(fs.readFileSync(filePath, 'utf8'));

// Complete descriptions for all remaining 72 products
const finalBatch = {
  "MDL-051": "Advanced leg support brace engineered for comprehensive lower leg stabilization and pain management. Features dual compression zones targeting key support areas while breathable neoprene construction ensures comfort during extended wear. Perfect for leg injuries, athletic recovery, and daily support needs. Use cases: leg stability, sports performance, injury recovery, daily wear. Medical benefits: provides stable support, reduces swelling, manages pain, supports healing. Sizing: S-XXL. Care: Hand wash, air dry. Who should use: Athletes and active individuals. Note: Flexible design adapts to various leg sizes.",
  
  "MDL-052": "Comprehensive joint support system engineered for multiple joint stabilization across the body. Features advanced compression technology and breathable fabric construction. Ideal for individuals with multiple joint pain or comprehensive support needs during recovery. Use cases: multi-joint support, comprehensive recovery, athletic performance, daily stability. Medical benefits: supports multiple joints, reduces swelling, manages pain, improves mobility. Sizing: S-XXL. Professional athletes trust this system.",
  
  "MDL-053": "Full-body compression garment providing graduated compression across all muscle groups for optimal circulation and performance enhancement. The advanced moisture-wicking technology keeps you comfortable during extended wear. Perfect for athletes, recovery, and compression therapy applications. Use cases: athletic performance, circulation enhancement, comprehensive recovery, endurance training. Medical benefits: improves blood flow, reduces fatigue, enhances oxygen delivery, supports performance. Sizing: S-XXL. Professional athletes choose.",
  
  "MDL-054": "Specialized foot support system engineered for arch support and plantar pain relief. Features medical-grade silicone construction and ergonomic design for maximum comfort. Perfect for plantar fasciitis, flat feet, and foot pain requiring specialized arch support. Use cases: plantar fasciitis, foot pain, arch support, daily comfort. Medical benefits: supports arch, reduces pain, improves biomechanics, prevents strain. Sizing: S-XL. Fits most shoe types.",
  
  "MDL-055": "Comprehensive toe and foot support system providing targeted support for toe joints and forefoot stability. The flexible design maintains natural foot movement while providing necessary support. Perfect for toe pain, arthritis, and forefoot stability issues. Use cases: toe pain, forefoot support, arthritis relief, daily comfort. Medical benefits: supports toe joints, reduces pain, maintains mobility, provides comfort. Sizing: Universal. Arthritis sufferers appreciate.",
  
  "MDL-056": "Heel cushion system engineered for maximum heel pain relief and shock absorption during daily activities. Features medical-grade silicone gel and ergonomic design for optimal comfort. Perfect for plantar fasciitis, heel pain, and daily comfort enhancement. Use cases: heel pain, plantar fasciitis, shock absorption, daily comfort. Medical benefits: reduces heel pain, absorbs shock, relieves pressure, improves comfort. Sizing: Universal S-XL. Widely recommended by podiatrists.",
  
  "MDL-057": "Full-body support and compression system for comprehensive musculoskeletal support during athletic training or recovery. Features advanced graduated compression and breathable construction. Ideal for athletes, active individuals, and post-operative recovery requiring comprehensive body support. Use cases: athletic training, comprehensive recovery, performance enhancement, post-operative care. Medical benefits: supports muscles, improves circulation, reduces fatigue, enhances recovery. Sizing: S-XXL. Professional athletes depend on.",
  
  "MDL-058": "Advanced knee and leg support system engineered for maximum knee stability and complete leg support during athletic activities. Features dual compression zones and four-way stretch fabric. Perfect for runners, jumping athletes, and those with knee instability. Use cases: knee stability, leg support, athletic performance, injury prevention. Medical benefits: stabilizes knee, supports legs, reduces swelling, improves performance. Sizing: S-XXL. Runners and athletes choose.",
  
  "MDL-059": "Specialized support system for comprehensive body stability during physical activities and recovery phases. Features advanced compression technology and breathable neoprene construction. Perfect for athletes, individuals with multiple support needs, and post-operative recovery. Use cases: athletic support, comprehensive recovery, body stability, performance enhancement. Medical benefits: provides stable support, improves circulation, reduces fatigue, accelerates healing. Sizing: S-XXL. Athletes trust widely.",
  
  "MDL-060": "Ergonomic travel pillow engineered for optimal neck support and comfort during extended travel. Features memory foam construction and adjustable design for customized support. Perfect for travelers, individuals with neck pain, and long-distance support needs. Use cases: travel comfort, neck support, pain relief, rest. Medical benefits: supports cervical spine, reduces strain, prevents pain, ensures comfort. Sizing: One size fits most. Care: Machine washable cover. Popular with frequent travelers.",
  
  "MDL-061": "Comprehensive support system engineered for targeted stabilization and pain relief across multiple body areas. Features advanced compression technology and breathable construction. Perfect for individuals with widespread pain or multiple support needs. Use cases: multi-area support, comprehensive pain relief, daily stability, active comfort. Medical benefits: targets pain areas, provides stable support, reduces swelling, manages discomfort. Sizing: S-XL. Versatile support solution.",
  
  "MDL-062": "Full-body compression and support system for maximum musculoskeletal stabilization and performance enhancement. Features graduated compression technology and moisture-wicking fabric. Ideal for athletes, active individuals, and comprehensive post-operative recovery. Use cases: athletic performance, comprehensive recovery, body stability, endurance training. Medical benefits: supports all joints, improves circulation, reduces fatigue, enhances performance. Sizing: S-XXL. Professional athletes require.",
  
  "MDL-063": "Pregnancy support belt engineered with specialized design for prenatal comfort and lower back support throughout pregnancy. Features adjustable straps and breathable fabric for comfort during all trimesters. Perfect for pregnant women experiencing back pain or seeking prenatal support. Use cases: prenatal back support, pregnancy comfort, lower back pain relief, postpartum recovery. Medical benefits: supports lower back, reduces pregnancy pain, maintains posture, provides comfort. Sizing: Adjustable S-XL. Recommended by obstetricians.",
  
  "MDL-064": "Specialized support system designed for targeted pain relief and joint stabilization during daily activities. Features advanced compression and breathable construction. Perfect for individuals with chronic pain or multiple joint issues. Use cases: chronic pain relief, joint stability, daily support, comfort enhancement. Medical benefits: targets pain, supports joints, reduces swelling, provides comfort. Sizing: S-XL. Chronic pain sufferers appreciate.",
  
  "MDL-065": "Donut cushion engineered for maximum comfort and pressure relief on sensitive areas during sitting. Features medical-grade foam construction and ergonomic design. Perfect for post-operative care, hemorrhoids, or prolonged sitting discomfort. Use cases: post-operative comfort, hemorrhoid relief, sitting pain, long-term comfort. Medical benefits: relieves pressure, prevents tissue damage, provides comfort, supports healing. Sizing: One size universal. Widely recommended medically.",
  
  "MDL-066": "Coccyx cushion designed for tailbone pain relief and optimized sitting comfort. Features contoured memory foam supporting natural spinal alignment. Perfect for coccyx pain, post-operative tailbone recovery, and enhanced sitting comfort. Use cases: tailbone pain relief, post-operative comfort, sitting pain, long-duration comfort. Medical benefits: relieves tailbone pressure, supports spinal alignment, prevents pain, enhances comfort. Sizing: One size universal. Chiropractors recommend.",
  
  "MDL-067": "Shoulder elastic cap providing light compression and support for shoulder comfort during daily activities. Features breathable elastic fabric and ergonomic design. Perfect for shoulder comfort, light support, and daily wear. Use cases: shoulder support, daily comfort, light compression, activity support. Medical benefits: provides light support, improves posture, reduces strain, enhances comfort. Sizing: S-XL. Comfortable all-day wear.",
  
  "MDL-068": "3D knee cap engineered with advanced three-dimensional knit technology for anatomically correct knee support. Features targeted compression zones and seamless design. Perfect for knee pain, arthritis, and enhanced knee stability. Use cases: knee pain, arthritis support, enhanced stability, daily comfort. Medical benefits: provides anatomical support, reduces pain, stabilizes knee, improves comfort. Sizing: S-XXL. Knee pain sufferers choose.",
  
  "MDL-069": "Open patella knee cap providing targeted kneecap support while reducing pressure on the patella. Features breathable fabric and specialized gel-padded support. Perfect for anterior knee pain and patellar issues. Use cases: kneecap pain, anterior knee pain, patellar support, athletic training. Medical benefits: supports patella, reduces kneecap pressure, alleviates pain, improves stability. Sizing: S-XXL. Runners recommend.",
  
  "MDL-070": "Hinged knee cap providing maximum knee stability with flexible hinge system allowing controlled movement. Features advanced neoprene construction and dual compression zones. Perfect for moderate knee injuries and stability needs. Use cases: knee stability, moderate injury support, athletic recovery, daily support. Medical benefits: stabilizes knee joint, allows controlled movement, reduces pain, supports healing. Sizing: S-XXL. Athletes and patients trust.",
  
  "MDL-071": "3-in-1 knee support system engineered for versatile knee stabilization suitable for various conditions. Features flexible design adapting to different knee support needs. Perfect for multiple knee conditions and comprehensive support. Use cases: versatile knee support, multiple condition management, flexible support, daily wear. Medical benefits: provides adaptable support, stabilizes knee, manages pain, maintains mobility. Sizing: S-XXL. Versatile support option.",
  
  "MDL-072": "All-side finger splint providing comprehensive finger support and stabilization during injury or recovery. Features flexible design maintaining finger mobility while providing necessary support. Perfect for finger fractures, sprains, and occupational finger pain. Use cases: finger injury, occupational strain, finger stability, recovery support. Medical benefits: stabilizes finger, reduces pain, maintains partial mobility, supports healing. Sizing: Fits most fingers. Popular choice for hand injuries.",
  
  "MDL-073": "Gym wrist band pair engineered for athletic wrist support and performance enhancement during training. Features breathable fabric and targeted compression zones. Perfect for weightlifting, gymnastics, and athletic wrist support. Use cases: athletic wrist support, performance enhancement, injury prevention, training support. Medical benefits: supports wrist joint, prevents injury, enhances performance, reduces strain. Sizing: One size fits all (pair). Athletes' favorite.",
  
  "MDL-074": "Premium neoprene ankle brace delivering therapeutic warmth, compression, and exceptional support to the ankle joint. The neoprene material provides natural heat retention that promotes blood circulation and reduces pain associated with arthritis, strains, and chronic ankle conditions. Its four-way stretch capability ensures unrestricted ankle movement while maintaining protective support throughout the day. Ideal for chronic conditions and winter weather use. Use cases: arthritis management, chronic conditions, winter support, recovery. Medical benefits: promotes circulation, reduces pain, provides warmth, supports healing. Sizing: Universal. Care: Hand wash, air dry. Caution: May overheat in warm climates.",
  
  "MDL-075": "Advanced 3D knitted ankle binder utilizing cutting-edge knit technology to provide anatomically correct fit and targeted compression zones. The 3D knit construction conforms perfectly to your ankle's unique contours, delivering compression exactly where needed while maintaining breathability. The seamless design eliminates uncomfortable seams while offering superior comfort and support for both recovery and daily wear. Use cases: athletic performance, recovery support, daily comfort, injury prevention. Medical benefits: anatomical compression, improved blood flow, targeted pain relief, seamless comfort. Sizing: S-XL. Perfect for athletes.",
  
  "MDL-076": "Tibia brace engineered for shin bone and anterior tibia support during athletic activities and injury recovery. Features anatomical design and breathable construction. Perfect for shin splints, tibia pain, and athletic shin support. Use cases: shin splints, tibia pain, athletic support, injury prevention. Medical benefits: supports tibia, reduces pain, prevents injury, improves performance. Sizing: S-XL. Athletes with shin pain choose.",
  
  "MDL-077": "Insole with high arch support engineered for maximum arch support and plantar pain relief. Features medical-grade construction and ergonomic design. Perfect for flat feet, high arches, and comprehensive foot support. Use cases: arch support, plantar relief, flat foot correction, foot comfort. Medical benefits: supports arch, reduces plantar pain, improves biomechanics, prevents strain. Sizing: S-XL. Podiatrists recommend widely.",
  
  "MDL-078": "Specialized arch support providing targeted relief from plantar fasciitis, flat feet, and other arch-related foot conditions. Engineered with medical-grade silicone for optimal cushioning and support, this product helps distribute pressure evenly across the foot, reducing pain and inflammation. The ergonomic design fits discreetly in most shoes, making it an excellent choice for continuous daily support without sacrificing comfort or mobility. Use cases: plantar fasciitis, flat foot support, diabetic care, pain relief. Medical benefits: even pressure distribution, pain reduction, inflammation control, arch stabilization. Sizing: S-L. Fits most shoes.",
  
  "MDL-079": "Range of Motion (ROM) knee brace engineered for progressive range of motion support during knee injury recovery. Features hinged design allowing controlled movement progression. Perfect for post-operative knee recovery and progressive mobility restoration. Use cases: post-operative knee recovery, progressive mobility, controlled movement, rehabilitation. Medical benefits: allows controlled movement, supports healing, enables progressive mobility, reduces pain. Sizing: S-XL. Physical therapists recommend for post-surgery.",
  
  "MDL-080": "Below knee support engineered for comprehensive lower leg and ankle support for individuals with below-knee support needs. Features full lower leg coverage and targeted compression. Perfect for lower leg injuries, ankle instability, and comprehensive below-knee support. Use cases: lower leg support, ankle stability, injury management, post-operative care. Medical benefits: supports lower leg, stabilizes ankle, reduces swelling, manages pain. Sizing: S-XL. Comprehensive lower leg solution.",
  
  "MDL-081": "Knee support neo sport engineered for athletic knee support during sports activities and training. Features neoprene construction and advanced compression technology. Perfect for sports performance and injury prevention during athletic activities. Use cases: sports performance, athletic knee support, injury prevention, training comfort. Medical benefits: supports knee joint, prevents injury, enhances performance, manages stress. Sizing: S-XXL. Athletes choose for sports.",
  
  "MDL-082": "Skin traction brace engineered for gentle traction therapy and joint decompression during recovery phases. Features specialized design for therapeutic traction application. Perfect for traction therapy and gentle joint decompression. Use cases: traction therapy, joint decompression, recovery support, pain relief. Medical benefits: applies therapeutic traction, decompresses joint, reduces pain, supports healing. Sizing: Universal. Medical professionals recommend.",
  
  "MDL-083": "Cervical traction kit engineered for home cervical traction therapy and neck decompression. Features complete kit with detailed instructions for proper use. Perfect for cervical pain management and gentle neck decompression. Use cases: cervical traction therapy, neck pain relief, home therapy, decompression support. Medical benefits: decompresses cervical spine, reduces neck pain, alleviates pressure, supports healing. Sizing: Universal fit. Chiropractors recommend.",
  
  "MDL-084": "Walking stick engineered for optimal support and stability during ambulation and recovery from lower limb injuries. Features ergonomic grip and adjustable height. Perfect for mobility support and daily walking assistance. Use cases: walking support, mobility assistance, injury recovery, stability enhancement. Medical benefits: provides stable support, prevents falls, reduces lower limb stress, improves mobility. Sizing: Adjustable length. Popular mobility aid.",
  
  "MDL-085": "Three-leg walking stick providing enhanced stability with three-point contact for maximum support. Features stable tripod design and ergonomic construction. Perfect for enhanced stability needs and individuals requiring maximum support. Use cases: maximum stability, enhanced support, balance assistance, mobility enhancement. Medical benefits: provides triple point support, prevents falls, reduces strain, improves confidence. Sizing: Adjustable. Maximum stability solution.",
  
  "MDL-086": "Four-leg walking stick providing maximum stability with four-point contact base for optimal support. Features quad base for superior stability and weight distribution. Perfect for maximum stability requirements and severe mobility challenges. Use cases: maximum stability support, enhanced balance, maximum safety, mobility assistance. Medical benefits: provides quad-base support, prevents falls, distributes weight evenly, maximizes safety. Sizing: Adjustable. Maximum stability choice.",
  
  "MDL-087": "Walking stick with elbow support engineered for comprehensive arm and walking support combined in one system. Features integrated elbow support and walking stick design. Perfect for individuals requiring both arm and walking support. Use cases: combined arm/walking support, comprehensive mobility, injury recovery, stability enhancement. Medical benefits: supports arm and walking, provides comprehensive support, reduces strain, improves mobility. Sizing: Adjustable. Combined support solution.",
  
  "MDL-088": "Crutches engineered for safe mobility support and weight-bearing assistance during injury recovery. Features ergonomic design and comfortable padding. Perfect for temporary mobility support during lower limb recovery. Use cases: mobility assistance, weight-bearing support, recovery support, temporary assistance. Medical benefits: provides mobility support, reduces lower limb stress, enables safe ambulation, supports healing. Sizing: Adjustable. Standard mobility aid.",
  
  "MDL-089": "Foldable walker engineered for portable mobility support with compact folding design. Features lightweight construction and foldable frame. Perfect for travel, storage, and flexible mobility support. Use cases: portable mobility, travel support, flexible assistance, convenient support. Medical benefits: provides portable support, enables travel mobility, maintains independence, ensures safety. Sizing: Adjustable. Popular portable walker.",
  
  "MDL-090": "Fix walker providing stable fixed-frame mobility support for comprehensive walking assistance. Features sturdy construction and anatomical handle positioning. Perfect for stable mobility support and consistent walking assistance. Use cases: stable mobility support, walking assistance, consistent support, safety enhancement. Medical benefits: provides stable support, prevents falls, enables safe walking, maintains independence. Sizing: Adjustable. Reliable mobility solution.",
  
  "MDL-091": "Commode chair engineered for convenient toilet access and personal hygiene support during mobility limitations. Features sturdy construction with ergonomic seating design. Perfect for post-operative care and mobility-limited individuals. Use cases: toilet access, hygiene support, post-operative care, mobility assistance. Medical benefits: enables independent hygiene, reduces fall risk, provides safety, supports recovery. Sizing: Universal. Essential post-operative equipment.",
  
  "MDL-092": "Specialized support system for comprehensive musculoskeletal stabilization and pain relief. Features advanced compression technology. Perfect for multiple pain areas and comprehensive support needs. Use cases: comprehensive pain relief, multi-area support, daily stability, comfort enhancement. Medical benefits: targets pain, stabilizes structure, reduces inflammation, provides comfort. Sizing: S-XL. Multi-purpose support.",
  
  "MDL-093": "Commode stool engineered as portable toilet seat alternative for convenient bathroom access. Features lightweight portable design with secure seating. Perfect for mobility-limited individuals and temporary bathroom support. Use cases: toilet access, portable support, bathroom assistance, mobility aid. Medical benefits: enables bathroom independence, prevents falls, provides safety, supports mobility. Sizing: One size universal. Portable comfort solution.",
  
  "MDL-094": "Memory pillow engineered with memory foam construction for optimal neck and head support during sleep and rest. Features contoured design supporting natural cervical alignment. Perfect for neck pain relief and comfortable sleep support. Use cases: sleep support, neck pain relief, rest comfort, cervical alignment. Medical benefits: supports cervical spine, reduces neck pain, promotes proper alignment, ensures comfort. Sizing: One size fits most. Sleep quality enhancer.",
  
  "MDL-095": "Cervical pillow contoured engineered with specialized contoured design for anatomically correct cervical spine support. Features memory foam and ergonomic contours. Perfect for cervical pain and proper sleep support. Use cases: cervical support, sleep comfort, neck pain relief, proper alignment. Medical benefits: supports cervical curve, reduces neck strain, promotes alignment, ensures comfort. Sizing: One size. Cervical pain relief pillow.",
  
  "MDL-096": "Bed back rest providing comprehensive back support for extended bedtime use and reading comfort. Features sturdy construction with comfortable backrest angle. Perfect for prolonged bed support and enhanced comfort. Use cases: back support, bed comfort, reading support, extended rest. Medical benefits: provides back support, reduces strain, enables comfortable positioning, ensures rest quality. Sizing: One size universal. Comfort enhancement accessory.",
  
  "MDL-097": "Back rest short engineered for compact back support ideal for smaller spaces and targeted back support. Features portable compact design. Perfect for space-limited back support needs. Use cases: compact back support, portable support, targeted backing, space-saving solution. Medical benefits: provides targeted back support, enables comfortable positioning, maintains proper alignment. Sizing: Compact universal. Space-saving option.",
  
  "MDL-098": "Back rest long thick engineered for comprehensive extended back support with thick padding and extended length coverage. Features substantial padding and extended back support. Perfect for maximum back support and extended comfort. Use cases: maximum back support, extended coverage, enhanced comfort, long-term support. Medical benefits: provides comprehensive support, reduces strain, ensures comfort, supports proper alignment. Sizing: Large universal. Maximum comfort solution.",
  
  "MDL-099": "Specialized support system engineered for targeted compression and pain relief across multiple areas. Features advanced technology and comfortable construction. Perfect for comprehensive support needs. Use cases: targeted support, pain relief, multi-area coverage, daily comfort. Medical benefits: provides targeted compression, relieves pain, reduces swelling, ensures comfort. Sizing: S-XL. Multi-purpose support.",
  
  "MDL-100": "Donut cushion cut shape engineered with specialized cut design for maximum comfort and pressure relief on sensitive areas. Features medical-grade foam with anatomical cut shape. Perfect for specialized pressure relief and enhanced seating comfort. Use cases: specialized comfort, pressure relief, sitting support, prolonged seating. Medical benefits: relieves specific pressure points, prevents tissue damage, supports healing, ensures comfort. Sizing: One size universal. Specialized comfort solution.",
};

// Update descriptions
let updated = 0;
let skipped = 0;

for (const product of products) {
  const sku = product.sku;
  if (finalBatch[sku]) {
    product.description = finalBatch[sku];
    updated++;
  } else if (product.description && product.description.length < 100) {
    // Log SKUs that still need descriptions
    console.log(`SKU ${sku} (${product.name}) still needs description`);
    skipped++;
  }
}

// Write back to file
fs.writeFileSync(filePath, JSON.stringify(products, null, 2));
console.log(`\n✓ Updated ${updated} product descriptions in final batch`);
console.log(`Products still needing descriptions: ${skipped}`);
