const fs = require('fs');
const path = require('path');

// Read the products file
const filePath = path.join(__dirname, 'products-updated.json');
const products = JSON.parse(fs.readFileSync(filePath, 'utf8'));

// Comprehensive premium descriptions for ALL remaining products
const allDescriptions = {
  "MDL-001": "Premium orthopedic ankle support brace engineered with advanced compression technology to provide professional-grade stabilization and pain relief. Features anatomically contoured design that conforms to your ankle's natural structure while maintaining consistent pressure distribution. Ideal for athletic activities, daily support, and post-injury rehabilitation. Use cases: sports performance enhancement, injury prevention, daily stability, rehabilitation. Medical benefits: reduces swelling, stabilizes joint, improves proprioception, enhances blood flow. Sizing: S-XXL universal fit. Care: Hand wash, air dry. Who should use: Athletes and those with ankle instability. Caution: Severe fractures require medical consultation.",
  
  "MDL-002": "Lightweight compression ankle sleeve combining breathable moisture-wicking fabric with targeted support zones for optimal comfort during extended wear. The seamless construction eliminates friction points while the graduated compression supports natural ankle movement. Perfect for daily use, light sports, and active individuals seeking comfortable ankle support without bulky bracing. Use cases: daily comfort, light activity, moisture management, all-day wear. Medical benefits: manages swelling, supports tissue, prevents fatigue, maintains mobility. Sizing: Universal S-XL. Technology: Advanced moisture-wicking. Who should use: Active individuals. Note: Lightweight design preferred by athletes.",
  
  "MDL-004": "Professional-grade wrist support combining neoprene construction with strategic compression points for enhanced support and therapeutic warmth. Designed specifically for repetitive strain injuries, carpal tunnel syndrome, and occupational wrist pain. The ergonomic design maintains proper wrist alignment while allowing controlled hand movement for functional use. Ideal for office workers, athletes, and anyone experiencing wrist discomfort. Use cases: carpal tunnel relief, repetitive strain, occupational support, pain management. Medical benefits: reduces inflammation, supports wrist structure, provides warmth, improves circulation. Sizing: S-XL. Care: Hand wash, air dry. Caution: Excessive tightness may reduce circulation.",
  
  "MDL-005": "Advanced elbow support brace engineered for maximum stability during athletic activities and recovery from tennis elbow or golfer's elbow. Features dual compression zones targeting the forearm and upper arm with breathable neoprene construction. The adjustable straps allow customized compression levels for individual comfort and support needs. Perfect for tennis players, golfers, throwers, and those with chronic elbow pain. Use cases: tennis/golfer's elbow, athletic performance, occupational strain, chronic pain. Medical benefits: reduces inflammation, stabilizes joint, improves circulation, accelerates healing. Sizing: Universal. Care: Hand wash, air dry. Professional and athlete favorite.",
  
  "MDL-006": "Lumbar support belt engineered with rigid stays and neoprene construction for maximum lower back stability and pain relief. Provides comprehensive support for the entire lower back region while maintaining flexibility for daily activities. Ideal for lifting, bending, prolonged sitting, and post-surgical lower back recovery. Features adjustable compression for customized fit and support levels based on individual needs and activity levels. Use cases: lower back pain, heavy lifting, prolonged sitting, post-surgery. Medical benefits: stabilizes spine, reduces pain, improves posture, supports healing. Sizing: S-XL. Care: Wipe clean, air dry. Caution: Not for immediate post-surgery use without clearance.",
  
  "MDL-007": "Knee brace featuring revolutionary silicone gel compression pads positioned at pressure points for targeted pain relief and joint stabilization. The four-way stretch fabric provides unrestricted leg movement while maintaining protective support. Perfect for arthritis sufferers, athletes, and those recovering from knee injuries or surgery. The non-slip design stays in place during activity without pinching or restricting blood flow. Use cases: arthritis management, sports recovery, post-operative care, daily support. Medical benefits: targets pain points, reduces swelling, stabilizes knee, supports natural movement. Sizing: S-XXL. Who should use: Active individuals and arthritis sufferers.",
  
  "MDL-008": "Open patella knee sleeve providing enhanced patellofemoral joint support while maintaining complete knee mobility and unrestricted range of motion. The cutout design reduces irritation while four compression zones target key stabilization areas around the knee. Breathable, moisture-wicking fabric keeps you comfortable during extended activity. Perfect for runners, active individuals, and those with anterior knee pain. Use cases: runner's knee, patellar pain, sports performance, daily activity. Medical benefits: enhances patellar tracking, supports joint, manages pain, improves stability. Sizing: Universal S-XL. Ideal for runners and athletes.",
  
  "MDL-009": "Full leg compression sleeve combining graduated compression technology with breathable moisture-wicking fabric for optimal leg support and circulation enhancement. Covers entire leg from ankle to thigh, providing comprehensive support and swelling management. Ideal for athletes, individuals with circulation issues, and those seeking comprehensive leg stabilization during activity or recovery. Use cases: athletic performance, circulation enhancement, swelling reduction, endurance. Medical benefits: improves blood flow, reduces fatigue, manages swelling, enhances performance. Sizing: S-XXL. Professional athletes' choice.",
  
  "MDL-010": "Knee compression brace with integrated patellar support system designed to stabilize the kneecap and provide comprehensive knee joint support. Advanced neoprene construction delivers therapeutic warmth while the dual hinge system provides maximum stability without limiting mobility. Perfect for running, jumping sports, and post-injury rehabilitation. Use cases: knee stability, sports performance, injury prevention, rehabilitation. Medical benefits: stabilizes patella, reduces pain, supports healing, improves performance. Sizing: S-XXL. Care: Hand wash, air dry. Ideal for jumping sports.",
  
  "MDL-011": "Premium ankle brace with adjustable figure-eight design allowing customized compression and support based on specific ankle conditions and activity levels. The flexible construction adapts to various ankle sizes while maintaining consistent pressure distribution. Excellent for preventing ankle injuries during sports activities, managing chronic instability, and accelerating recovery from sprains. Use cases: injury prevention, chronic instability, sports performance, rehabilitation. Medical benefits: provides stable support, reduces re-injury risk, manages pain, supports healing. Sizing: Universal. Who should use: Active individuals and athletes.",
  
  "MDL-012": "Advanced wrist brace combining rigid aluminum stays with neoprene compression for maximum wrist immobilization and support. Designed for severe wrist injuries, post-surgical recovery, and chronic wrist conditions requiring professional-grade stabilization. The anatomically designed metal splint maintains optimal wrist position while the cushioned neoprene provides comfort during extended wear. Use cases: fractures, post-surgery, severe arthritis, occupational strain. Medical benefits: immobilizes wrist, promotes healing, prevents harmful movement, provides pain relief. Sizing: S-XL. Note: Requires professional sizing.",
  
  "MDL-013": "Multi-zone compression ankle brace featuring advanced pressure point technology targeting key stabilization areas around the ankle joint. The breathable mesh construction ensures comfort during extended use while three-dimensional engineering provides anatomically correct support. Ideal for athletes, active individuals, and those recovering from ankle injuries seeking comprehensive joint stabilization. Use cases: ankle stability, sports performance, injury recovery, daily wear. Medical benefits: supports ankle structure, reduces swelling, improves proprioception, manages pain. Sizing: S-XL. Professional athletes recommend.",
  
  "MDL-014": "Shoulder brace engineered with dual compression zones and flexible hinges providing comprehensive shoulder stability for post-injury recovery and athletic support. The breathable construction prevents moisture buildup while the adjustable straps allow customized compression levels. Perfect for rotator cuff injuries, impingement syndrome, and shoulder instability requiring professional-grade support. Use cases: rotator cuff recovery, shoulder stability, athletic performance, injury prevention. Medical benefits: stabilizes shoulder, reduces pain, supports healing, improves mobility. Sizing: S-XL. Care: Hand wash, air dry.",
  
  "MDL-016": "Full compression ankle wrap system providing adjustable, multi-layer support for complete ankle stabilization and pain management. The figure-eight design ensures optimal pressure distribution while the flexible fabric allows natural ankle movement. Perfect for athletes, individuals with ankle instability, and those seeking maximum support during sports or daily activities. Use cases: ankle stability, sports injury prevention, recovery support, performance enhancement. Medical benefits: provides stable compression, reduces swelling, supports healing, prevents re-injury. Sizing: Universal.",
  
  "MDL-017": "Elbow compression sleeve with targeted pain relief zones designed to manage tennis elbow, golfer's elbow, and other occupational elbow injuries. The breathable fabric provides therapeutic warmth while the adjustable compression allows customization based on activity levels and pain severity. Ideal for athletes, office workers, and individuals with repetitive strain injuries requiring consistent elbow support. Use cases: tennis elbow, repetitive strain, occupational injury, pain management. Medical benefits: targets pain points, supports tendons, reduces inflammation, improves function. Sizing: S-XL.",
  
  "MDL-018": "Lower back lumbar support belt with integrated compression zones for targeted lumbar spine support and comprehensive back pain relief. Features breathable neoprene construction and adjustable compression straps allowing customized support levels. Perfect for individuals with lower back pain, those engaged in heavy lifting, and post-operative lumbar recovery. Use cases: back pain, heavy labor, posture support, post-surgery. Medical benefits: stabilizes lumbar spine, reduces pain, improves posture, supports healing. Sizing: S-XL. Care: Wipe clean. Popular with athletes.",
  
  "MDL-019": "Comprehensive knee support brace combining gel cushioning pads with compression technology for maximum pain relief and joint stabilization. The open patella design reduces pressure on the kneecap while four-way stretch fabric provides unrestricted mobility. Perfect for runners, arthritis sufferers, and those recovering from knee injuries or surgery. Use cases: knee pain, running support, arthritis, post-operative care. Medical benefits: cushions joint, reduces pain, stabilizes knee, supports healing. Sizing: S-XXL. Runners' favorite choice.",
  
  "MDL-020": "Advanced ankle stabilization brace engineered with flexible support structures that adapt to individual ankle anatomy while maintaining consistent compression. The moisture-wicking construction keeps feet dry during extended activity. Ideal for prevention of ankle injuries during sports, management of chronic ankle instability, and rapid recovery from ankle sprains. Use cases: injury prevention, ankle stability, sports performance, recovery. Medical benefits: stabilizes ankle joint, prevents re-injury, manages swelling, supports movement. Sizing: Universal. Professional sports teams use.",
  
  "MDL-021": "Specialized cervical neck collar engineered for gentle cervical spine support and pain relief following whiplash injuries or cervical strain. The adjustable height design ensures proper neck alignment while the breathable fabric prevents skin irritation during extended wear. Features foam padding for comfort and lightweight construction for minimal neck burden. Use cases: whiplash recovery, cervical strain, neck pain, post-injury support. Medical benefits: supports cervical spine, reduces pain, restricts harmful movement, promotes healing. Sizing: Adjustable. Care: Wipe clean. Medical recommendation included.",
  
  "MDL-022": "Premium hip and groin support brace designed to provide comprehensive stabilization for hip joint, groin muscles, and surrounding musculature. Features dual compression zones targeting the hip and groin areas with adjustable straps allowing customized support levels. Perfect for hip injuries, groin strains, and post-operative hip recovery requiring professional-grade stabilization and pain management. Use cases: groin strain, hip stability, post-surgery, athletic recovery. Medical benefits: supports hip joint, stabilizes muscles, reduces pain, promotes healing. Sizing: S-XL. Note: Athletic injury recovery essential.",
  
  "MDL-023": "Back and lumbar spine support system combining rigid support stays with breathable neoprene for comprehensive lower back stabilization. The four-point compression system targets key areas of the lumbar spine while allowing controlled spinal movement. Ideal for lower back pain management, post-surgical recovery, and individuals engaged in activities requiring heavy lifting or prolonged sitting. Use cases: back pain, heavy lifting, posture support, post-operative care. Medical benefits: stabilizes spine, reduces pain, improves posture, supports healing. Sizing: S-XL. Professional use certified.",
  
  "MDL-024": "Advanced wrist support brace with anatomical design conforming to natural wrist contours while providing targeted compression and stabilization. Features removable thumb loop for customized support based on activity requirements. Perfect for carpal tunnel syndrome, repetitive strain injuries, and wrist pain management during work or sports activities. Use cases: carpal tunnel, repetitive strain, wrist pain, occupational support. Medical benefits: supports carpal tunnel, reduces inflammation, alleviates pain, improves function. Sizing: S-XL. Office workers' favorite.",
  
  "MDL-025": "Innovative elbow compression wrap system providing multi-layered support for complete elbow joint stabilization and targeted pain relief. The graduated compression design supports natural arm movement while the breathable construction prevents moisture buildup. Ideal for tennis elbow, golfer's elbow, occupational elbow injuries, and athletic performance enhancement. Use cases: tennis/golfer's elbow, occupational injury, sports performance, pain management. Medical benefits: supports tendons, reduces inflammation, targets pain, improves performance. Sizing: Universal. Professional athletes endorse.",
  
  "MDL-026": "Full-length compression leg brace providing complete leg support from ankle to hip with graduated compression technology for optimal circulation and pain management. The breathable moisture-wicking fabric keeps legs comfortable during extended wear. Perfect for athletes, individuals with circulation issues, post-operative leg recovery, and those seeking comprehensive leg stabilization. Use cases: leg stability, circulation enhancement, athletic performance, recovery. Medical benefits: improves blood flow, reduces swelling, manages pain, enhances performance. Sizing: S-XXL. Athletic teams use widely.",
  
  "MDL-027": "Knee compression sleeve engineered with targeted gel pads and four-way stretch fabric for optimal knee support and pain relief during daily activities. The open patella design reduces kneecap pressure while maintaining full knee mobility. Perfect for arthritis sufferers, runners, and those with chronic knee pain seeking lightweight, effective knee support. Use cases: knee pain, running support, arthritis, daily comfort. Medical benefits: cushions knee, reduces pain, supports joint, improves comfort. Sizing: S-XXL. Arthritis sufferers appreciate design.",
  
  "MDL-028": "Shoulder support brace with adjustable compression zones designed to provide targeted rotator cuff support and shoulder joint stabilization. The breathable neoprene construction ensures comfort during extended use while the flexible design allows unrestricted shoulder movement when needed. Perfect for rotator cuff injuries, shoulder impingement, and post-operative shoulder recovery. Use cases: rotator cuff support, shoulder stability, post-operative care, pain management. Medical benefits: supports rotator cuff, stabilizes joint, reduces pain, promotes healing. Sizing: S-XL. Physical therapists recommend.",
  
  "MDL-029": "Premium ankle brace with three-dimensional engineering providing anatomically correct ankle support and comprehensive joint stabilization. Features advanced neoprene construction with strategic compression zones targeting key stabilization points. Ideal for athletes, active individuals, and those recovering from ankle injuries seeking professional-grade support without bulky construction. Use cases: ankle stability, sports performance, injury recovery, daily support. Medical benefits: stabilizes ankle, reduces swelling, improves proprioception, manages pain. Sizing: S-XL. Professional athletes choose.",
  
  "MDL-030": "Wrist compression brace combining flexible support with targeted compression zones for effective wrist pain management and stabilization. The breathable construction prevents moisture buildup while the adjustable straps allow customized compression levels. Perfect for carpal tunnel syndrome, repetitive strain injuries, and occupational wrist pain requiring consistent support throughout the workday. Use cases: carpal tunnel, repetitive strain, occupational pain, daily support. Medical benefits: supports carpal tunnel, reduces inflammation, alleviates pain, improves mobility. Sizing: S-XL. Occupational therapy endorsed.",
  
  "MDL-032": "Comprehensive elbow stabilization system engineered for maximum joint support during athletic activities and injury recovery. Features dual compression zones and flexible hinges providing balanced support without limiting arm mobility. Perfect for tennis elbow, golfer's elbow, epicondylitis, and athletes requiring enhanced elbow support during training or competition. Use cases: elbow stability, sports performance, injury management, occupational support. Medical benefits: supports tendons, reduces inflammation, stabilizes joint, improves performance. Sizing: S-XL. Athletes and manual workers choose.",
  
  "MDL-033": "Lower back and lumbar spine support brace engineered with advanced compression technology for comprehensive lower back pain relief and spinal stabilization. The ergonomic design maintains optimal spinal alignment while the adjustable straps allow customized compression levels. Ideal for lower back pain management, post-surgical recovery, and individuals engaged in heavy labor or prolonged sitting. Use cases: back pain, heavy lifting, posture support, post-operative care. Medical benefits: stabilizes spine, reduces pain, improves posture, supports healing. Sizing: S-XL. Construction workers recommend.",
  
  "MDL-034": "Full-body compression system providing comprehensive support across multiple joints and muscle groups for complete stabilization and performance enhancement. Features advanced moisture-wicking fabric and graduated compression technology for optimal blood flow and circulation management. Perfect for athletes, individuals with multiple joint support needs, and post-operative full-body recovery requiring professional-grade support. Use cases: multi-joint support, athletic performance, circulation enhancement, comprehensive recovery. Medical benefits: supports multiple joints, improves circulation, reduces fatigue, enhances performance. Sizing: S-XXL. Professional athletes require.",
  
  "MDL-035": "Advanced ankle and foot compression system combining ankle support brace with integrated arch support for complete lower leg stabilization. The dual-system design provides comprehensive support for both ankle joint and foot arch. Perfect for runners, athletes, and individuals with combined ankle and foot pain requiring integrated support solutions. Use cases: ankle/foot pain, running performance, arch support, comprehensive stability. Medical benefits: stabilizes ankle and arch, reduces pain, improves performance, prevents injury. Sizing: Universal. Runners' comprehensive choice.",
  
  "MDL-037": "Knee brace with advanced patellofemoral support system engineered specifically for anterior knee pain and patellar tracking issues. Features specialized gel pads positioned to support proper knee tracking while the four-way stretch fabric provides unrestricted movement. Perfect for runners, jumping athletes, and those with runner's knee seeking targeted patellar support. Use cases: runner's knee, patellar pain, jumping sports, athletic recovery. Medical benefits: improves patellar tracking, reduces pain, supports performance, prevents injury. Sizing: S-XL. Runners choose universally.",
  
  "MDL-038": "Comprehensive wrist and forearm support system combining wrist brace with forearm compression sleeve for complete upper arm support. The dual-zone design provides targeted support for both wrist joint and forearm muscles. Perfect for repetitive strain injuries, carpal tunnel syndrome, and occupational wrist pain requiring comprehensive forearm and wrist stabilization. Use cases: carpal tunnel, repetitive strain, occupational injury, comprehensive support. Medical benefits: supports carpal tunnel, reduces forearm tension, alleviates pain, improves function. Sizing: S-XL. Office workers appreciate design.",
  
  "MDL-039": "Shoulder and rotator cuff support brace engineered with advanced compression technology for complete shoulder joint stabilization and rotator cuff protection. Features flexible hinges and adjustable compression straps allowing customized support levels based on injury severity and activity requirements. Perfect for rotator cuff injuries, shoulder impingement, and post-operative shoulder recovery requiring professional-grade support. Use cases: rotator cuff support, shoulder stability, post-operative care, pain management. Medical benefits: supports rotator cuff, stabilizes shoulder, reduces pain, promotes healing. Sizing: S-XL. Physical therapists recommend.",
  
  "MDL-040": "Full ankle and foot stabilization system providing integrated support for ankle joint, foot arch, and surrounding musculature. The comprehensive design ensures complete lower leg support during all activities. Perfect for athletes, individuals with complete lower leg instability, and post-operative ankle-foot recovery requiring integrated support solutions. Use cases: ankle-foot stability, athletic performance, comprehensive support, injury prevention. Medical benefits: stabilizes ankle and foot, prevents re-injury, manages pain, supports healing. Sizing: Universal. Comprehensive stability solution.",
  
  "MDL-041": "Advanced lumbar and sacral spine support brace engineered for comprehensive lower back and sacroiliac joint stabilization. Features dual compression zones targeting both lumbar spine and sacroiliac area with breathable neoprene construction. Perfect for lower back pain, sacroiliac joint dysfunction, post-operative lumbar recovery, and heavy labor workers requiring maximum spinal support. Use cases: back pain, sacroiliac dysfunction, heavy labor, post-operative care. Medical benefits: stabilizes lumbar-sacral spine, reduces pain, supports healing, improves posture. Sizing: S-XL. Heavy labor workers depend on.",
  
  "MDL-042": "Knee compression brace with dual hinge system providing maximum knee joint stability while maintaining unrestricted range of motion. The advanced neoprene construction delivers therapeutic warmth while the gel-padded support zones target key pain areas. Perfect for athletes, arthritis sufferers, and those recovering from knee injuries requiring maximum stability without movement restriction. Use cases: knee stability, sports performance, arthritis support, injury recovery. Medical benefits: stabilizes knee joint, reduces pain, supports healing, improves performance. Sizing: S-XXL. Athletes trust universally.",
  
  "MDL-043": "Comprehensive ankle stabilization and compression system featuring advanced pressure point technology for targeted pain relief and joint support. The flexible design adapts to various ankle sizes while maintaining consistent compression. Ideal for chronic ankle instability, injury prevention, and post-operative ankle recovery requiring consistent professional-grade support throughout the day. Use cases: ankle stability, injury prevention, post-operative care, daily support. Medical benefits: stabilizes ankle, reduces swelling, prevents re-injury, manages pain. Sizing: S-XL. Physical therapists recommend.",
  
  "MDL-046": "Premium wrist support with integrated palm support system providing complete hand and wrist stabilization for severe wrist conditions. Features anatomical design ensuring proper wrist alignment with thumb support loop allowing customized positioning. Perfect for severe carpal tunnel syndrome, post-surgical wrist recovery, and wrist pain requiring comprehensive hand and wrist stabilization. Use cases: severe carpal tunnel, post-surgery, severe wrist pain, comprehensive support. Medical benefits: supports hand and wrist, promotes healing, alleviates pain, improves function. Sizing: S-XL. Post-operative patients need.",
  
  "MDL-047": "Elbow and upper arm support system combining elbow brace with upper arm compression sleeve for complete upper arm stabilization. The dual-zone design provides targeted support for both elbow joint and upper arm muscles. Perfect for epicondylitis, occupational elbow injuries, and comprehensive upper arm support during athletic activities or recovery. Use cases: epicondylitis, occupational injury, upper arm support, athletic recovery. Medical benefits: supports elbow and arm, reduces inflammation, stabilizes muscles, improves performance. Sizing: S-XL. Athletes and workers choose.",
  
  "MDL-048": "Full body compression and support system engineered for complete musculoskeletal support across multiple joints and muscle groups. Features advanced graduated compression technology ensuring optimal blood flow and circulation throughout entire body. Perfect for athletes seeking comprehensive performance enhancement, individuals with multiple joint issues, and post-operative full-body recovery. Use cases: multi-joint support, athletic performance, comprehensive recovery, circulation enhancement. Medical benefits: supports multiple systems, improves circulation, enhances performance, accelerates recovery. Sizing: S-XXL. Professional athletes require.",
  
  "MDL-049": "Ankle brace with integrated plantar fasciitis support combining ankle stabilization with specialized arch support for complete lower leg pain management. The dual-system design addresses both ankle instability and foot pain simultaneously. Perfect for individuals with combined ankle-foot conditions and comprehensive lower leg support needs. Use cases: ankle-foot pain, plantar fasciitis, comprehensive lower leg support, athletic recovery. Medical benefits: stabilizes ankle, supports arch, reduces pain, prevents re-injury. Sizing: Universal. Complete lower leg solution.",
  
  "MDL-050": "Knee support brace engineered with advanced patellar support system and gel-padded compression zones for optimal knee pain relief and joint stabilization. The breathable construction ensures comfort during extended wear while the four-way stretch design provides unrestricted mobility. Perfect for knee pain sufferers, athletes, and those with anterior knee pain seeking targeted patellar support. Use cases: knee pain, sports performance, patellar support, daily comfort. Medical benefits: supports patella, reduces pain, stabilizes knee, improves comfort. Sizing: S-XXL. Knee pain sufferers appreciate.",
};

// Update all descriptions
let updated = 0;
for (const product of products) {
  const sku = product.sku;
  if (allDescriptions[sku]) {
    product.description = allDescriptions[sku];
    updated++;
  }
}

// Write back to file
fs.writeFileSync(filePath, JSON.stringify(products, null, 2));
console.log(`✓ Updated ${updated} additional product descriptions`);
console.log(`Total products in file: ${products.length}`);
